data_params:
  boundary_only: false
  dataset: XOR
  knowledge_func: counterfactual
  max_delta: 1.0
  n_vec: 1
  train_size: 30
  validation_size: 200
hyperparams:
  batch_size: 32
  epochs: 30
  learning_rate: 0.01
  loss_function: multiclass_cross_entropy
  loss_mix: 0.5
  model: multiclass
  model_io: !!python/tuple
  - 64
  - 2
  model_size: !!python/tuple
  - 80
  - 1
  momentum: 0.5
  seed: 42
visualisation:
  draw_eval: true
  plot_epoch: False
  visualise: False
  video: False
