data_params:
  active_sampling: False
  boundary_only: false
  control: False
  dataset: integer_len32
  diversity: 0.99
  knowledge_func: counterfactual
  max_delta: 1.0
  n_vec: 2
  init_samplesize: 60
  sample_size: 30
  train_size: 100
  validation_size: 100
hyperparams:
  batch_size: 32
  embedding_size: 64
  epochs: 60
  learning_rate: 0.001
  loss_function: multiclass_split_loss_embedding_sign #multiclass_cross_entropy # # # # # # # # #  # #multiclass_split_gs_embedding # # # # # # #multiclass_split_loss_embedding_softplus # #  # # # # # # # # # #combined_loss_embedding_gs
  loss_mix: 0.3
  model: multiclass_bag_of_words #bag_of_words
  model_io: !!python/tuple
  - 8
  - 1
  model_size: !!python/tuple
  - 8
  - 1
  momentum: 0.5
  n_models: 1
  seed: 100
  vocabulary_size: 20002
visualisation:
  draw_eval: false
  plot_epoch: false
  video: false
  visualise: false
  visualise_embeddings: False
