data_params:
  active_sampling: false
  boundary_only: false
  dataset: integer_len32
  diversity: 0.8
  init_samplesize: 200
  knowledge_func: counterfactual
  max_delta: 1.0
  n_vec: 2
  sample_size: 60
  train_size: 10
  validation_size: 100
hyperparams:
  batch_size: 32
  embedding_size: 50
  epochs: 5
  learning_rate: 0.0001
  loss_function: combined_loss_embedding_sign
  loss_mix: 0.5
  model: bag_of_words
  model_io: !!python/tuple
  - 8
  - 1
  model_size: !!python/tuple
  - 80
  - 1
  momentum: 0.5
  n_models: 1
  seed: 100
  vocabulary_size: 20002
visualisation:
  draw_eval: false
  plot_epoch: false
  video: false
  visualise: false
