data_params:
  boundary_only: false
  dataset: integer_len40__connected_False__path_pca__length_local
  knowledge_func: counterfactual
  max_delta: 1.0
  n_vec: 2
  train_size: 20
  validation_size: 100
hyperparams:
  batch_size: 8
  embedding_size: 32
  epochs: 30
  learning_rate: 0.01
  loss_function: multiclass_cross_entropy
  loss_mix: 0.5
  model: mnist_conv_gemini
  model_io: !!python/tuple
  - 8
  - 1
  model_size: !!python/tuple
  - 8
  - 1
  momentum: 0.5
  n_models: 1
  seed: 100
  vocabulary_size: 20001
visualisation:
  draw_eval: true
  plot_epoch: false
  video: false
  visualise: true
