data_params:
  boundary_only: false
  dataset: Circles
  knowledge_func: counterfactual #_breadcrumbs
  max_delta: 1.0
  n_vec: 1
  train_size: 6
  validation_size: 1000
  control: False
  active_sampling: False
  init_samplesize: 10
  sample_size: 5
  diversity: 0.8
hyperparams:
  batch_size: 32
  embedding_size: 512
  # embedding_size: 128
  epochs: 100
  learning_rate: 0.001
  loss_function: multiclass_gs_2d_wrapper #multiclass_split_loss # #multiclass_cross_entropy 
  loss_mix: 0.5
  model: simple_v2
  model_io: !!python/tuple
  - 8
  - 2
  model_size: !!python/tuple
  - 80
  - 1
  momentum: 0.5
  n_models: 6
  seed: 1
visualisation:
  draw_eval: False
  plot_epoch: False
  video: False
  visualise: False
  visualise_embeddings: False

