{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16ae3a95",
   "metadata": {},
   "outputs": [],
   "source": [
    "import jax\n",
    "import jax.numpy as jnp\n",
    "from jax import grad, vmap, random\n",
    "from flax import linen as nn\n",
    "import optax\n",
    "\n",
    "\n",
    "# ----- Simple model definition -----\n",
    "class SimpleModel(nn.Module):\n",
    "    features: int\n",
    "\n",
    "    @nn.compact\n",
    "    def __call__(self, x):\n",
    "        x = nn.Dense(self.features)(x)\n",
    "        x = nn.relu(x)\n",
    "        x = nn.Dense(1)(x)\n",
    "        return x.squeeze(-1)\n",
    "\n",
    "\n",
    "# ----- Predict wrapper for gradient computation -----\n",
    "def predict_wrapper(params, model, x, rng):\n",
    "    return model.apply(params, x, rngs={\"dropout\": rng})\n",
    "\n",
    "\n",
    "# ----- Main directional derivative test -----\n",
    "def main():\n",
    "    key = random.PRNGKey(0)\n",
    "    rng, init_rng = random.split(key)\n",
    "\n",
    "    model = SimpleModel(features=8)\n",
    "\n",
    "    # Fake batch of 6 examples, input dim = 2\n",
    "    X = jnp.array([[1., 0.], [1., 0.], [1., 0.], [-1., 0.], [-1., 0.], [-1., 0.]])\n",
    "    K = jnp.array([[1., 0.], [1., 0.], [1., 0.], [-1., 0.], [-1., 0.], [-1., 0.]])\n",
    "\n",
    "    variables = model.init(init_rng, X)\n",
    "    params = variables['params']\n",
    "\n",
    "    # Compute ∇f(x) for each x in the batch\n",
    "    grad_fn = grad(predict_wrapper, argnums=2)\n",
    "    batched_grad_fn = vmap(grad_fn, in_axes=(None, None, 0, None), out_axes=1)\n",
    "\n",
    "    g = batched_grad_fn(params, model, X, rng)  # Shape: (D, N)\n",
    "\n",
    "    print(\"Gradient shape (D, N):\", g.shape)\n",
    "    print(\"Gradients g:\\n\", g)\n",
    "\n",
    "    # Compute directional derivatives K_i · ∇f(x_i)\n",
    "    def dot_rows(a_row, b_row):\n",
    "        return jnp.dot(a_row, b_row)\n",
    "\n",
    "    # Transpose g to (N, D) to match K's shape\n",
    "    g_T = g.T\n",
    "\n",
    "    directional_derivative = vmap(dot_rows)(K, g_T)\n",
    "    print(\"Directional derivative shape:\", directional_derivative.shape)\n",
    "    print(\"Directional derivative values:\\n\", directional_derivative)\n",
    "\n",
    "    # Check if this directional derivative is differentiable w.r.t. params\n",
    "    def dd_loss(params):\n",
    "        g = batched_grad_fn(params, model, X, rng)\n",
    "        g_T = g.T\n",
    "        dd = vmap(dot_rows)(K, g_T)\n",
    "        return jnp.mean(dd ** 2)\n",
    "\n",
    "    dd_grad = grad(dd_loss)(params)\n",
    "    flat_grads, _ = jax.flatten_util.ravel_pytree(dd_grad)\n",
    "\n",
    "    print(\"Gradient norm w.r.t. params:\", jnp.linalg.norm(flat_grads))\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6df1fb24",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
