data_params:
  boundary_only: false
  dataset: integer_len32_SIZE_all
  knowledge_func: counterfactual
  max_delta: 1.0
  n_vec: 2
  train_size: 10
  n_classes: 4
  validation_size: 100
  active_sampling: True
  sample_size: 25
  diversity: 0.8
hyperparams:
  n_models: 6
  batch_size: 32
  epochs: 50
  learning_rate: 0.0001
  loss_function:  multiclass_combined_loss_embedding  #multiclass_cross_entropy #  # #multiclass_gradient_supervision_embedding
  loss_mix: 0.5
  model: multiclass_bag_of_words
  # num_classes: 4
  vocabulary_size: 20002
  embedding_size: 128
  model_io: !!python/tuple
  - 8
  - 1
  model_size: !!python/tuple
  - 8
  - 1
  momentum: 0.5
  seed: 100
visualisation:
  draw_eval: true
  plot_epoch: false
  video: false
  visualise: true
