data_params:
  boundary_only: false
  dataset:  integer_len1000__connected_True__path_face__split__boundary_True #integer_len200__connected_True__path_face__split__boundary_True #paths/mnist_paths_data_split_50paths #Projects/MNIST_FACE/data/paths/ 
  knowledge_func: counterfactual
  max_delta: 1.0
  n_vec: 2
  train_size: 20
  validation_size: 100
  control: False
  active_sampling: False
  init_samplesize: 50
  sample_size: 25
  diversity: 0.8
hyperparams:
  batch_size: 8
  embedding_size: 64
  epochs: 20
  learning_rate: 0.0001 #0.0001
  loss_function: multiclass_split_loss_embedding_softplus #multiclass_cross_entropy # # # # # # # multiclass_split_gs_embedding # # # # # # 
  loss_mix: 0.3
  model:  optimized_mnist_conv #simple_mnist_conv #manifold_robust_mnist_conv # # #mnist_conv_gemini # mnist_vit #
  model_io: !!python/tuple
  - 8
  - 1
  model_size: !!python/tuple
  - 8
  - 1
  momentum: 0.5
  n_models: 6
  seed: 100
  vocabulary_size: 20001
visualisation:
  draw_eval: false
  plot_epoch: false
  video: false
  visualise: false
  visualise_embeddings: false
